### PR TITLE
Update an item Api working with keys price and quantity

### LINKED ISSUE #5: Be able to update item(s)
**As a** User
 **I need** a function that updates the item in a shopcart  
 **So that** I can change the number of the item I need
   
 ### Assumptions
 * Every Product has a unique ID
 * Every Shopping Cart has a unique ID
 * Only the owner of the Shopping Cart can modify items in it
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that the shopping cart does not exist
 When I call 'PUT /shopcarts/{id}/items/{id}'
 Then return an error as the shopping cart does not exist

 Given that the product does not exist in the shopping cart
 When I call 'PUT /shopcarts/{id}/items/{id}'
 Then go to the Add Item instead, and then update the item

 Given that the product exists in the shopping cart
 When I call 'PUT /shopcarts/{id}/items/{id}'
 Then update the number of the item to numOfItem
 ```

### LINKED ISSUE #39: We don't have an API to update an item in a Shopcart.
**Describe the bug**
We don't have an API to update an item in a Shopcart (`PUT`).

**To Reproduce**
1. `PUT` something like `/shopcarts/<id>/items/<item_id>`

**Expected behavior**
- Updates with provided JSON content.
- Returns `HTTP 404` if no such resource exists.

**Actual Behavior**
- Our current service returns `HTTP 405 Method Not Allowed`.

**Additional context**
From Feedback for Sprint 1.

### PR DESCRIPTION
**Pull request by sweta1947**
- #5 
- #39

### CODE REVIEW

**Comment by sweta1947** [comment]
How to connect this pull request to two issues?

**Review by allenpthuang — COMMENTED** [review]
@sweta1947 thanks for the pull! LGTM, but you might need to merge conflicts first.

**Review by allenpthuang — APPROVED** [review]
LGTM, thanks!

**Review by yuheng-lu — APPROVED** [review]
Hi Sweta, thanks for your PR! Everything looks good. One thing to notice is that you might want to connect the two issues you resolved with the PR, also on Zenhub. If you scroll down to the bottom of New Issues on Zenhub, you will find this PR is actually listed under New Issues. Click Connect Issue button and connect with the two issues you resolved, then I think you are all set! Thank you!
Screen Shot 2022-11-29 at 14 18 53

**Comment by sweta1947** [comment]
Thanks @Yuheng-Lu

**Pull request merged**
