### PR TITLE
Delete an Item from a Shopcart

### LINKED ISSUE #3: Delete an item from a shopcart
**As a** User
**I need** to be able to delete a specific item or item(s) from the existing shopcart
**So that** remove the item(s) I do not want any more

**Assumptions:**
* Every product should have a unique product id
* Only the owner of the shopcart can delete the item(s). That is to say, we will need authorization.

**Acceptance Criteria**
```
Given that the item does not exist
When I call 'DELETE /shopcarts/{id}/items/{id}'
Then I should get the error message "Cannot find the item"
Given that the item does exist
When I call  'DELETE /shopcarts/{id}/items/{id}'
The item corresponding to the id should be removed successfully
```

### PR DESCRIPTION
**Pull request by yuheng-lu**

### CODE REVIEW

**Comment by allenpthuang** [comment]
Hi Yuheng,

Thanks for the PR! Ditto in #25.

**Comment by yuheng-lu** [comment]
Thank you, Allen! For some reason, I accidentally deleted _create_items in the last push. Now the problem is fixed.

**Comment by allenpthuang** [comment]
Thanks for the fix!
Do you want to rebase this branch onto your `dev/addAnItemToShopcart`? Current branch will fail in `nosetests` because in the test codes, you have
```
self.client.post(
            f"{BASE_URL}/{shopcart.id}/items", json=item.serialize(), content_type="application/json"
        )
```
which cannot happen if the route in `dev/addAnItemToShopcart` is not available.

**Comment by yuheng-lu** [comment]
Fixed. Now it is supposed to work.

**Review by allenpthuang — APPROVED** [review]
Thanks, Yuheng!

**Review by huwwww — APPROVED** [review]

**Pull request merged**
